### ISSUE TITLE
Change environment variable names to reflect changes in the official image

### ISSUE THREAD

**Issue by BadWolf97** [yobasystems/alpine-mariadb#74] opened 2024-02-04 14:35 UTC
The official mariadb-Image uses `MARIADB_*` instead of `MYSQL_*` names for Passwords etc.
For this image to be a drop-in replacement for the official mariadb-image, these should be changed as well.

**Comment by dominictayloruk** [comment] 2024-02-04 19:01
Duplicate of https://github.com/yobasystems/alpine-mariadb/issues/60

**Closed as completed** 2024-02-04 19:01 UTC
